---
title: "Ranking of strategies"
tab_label: "matches" 
output: html_document
---

```{r "init_data", include=FALSE}
library(StratTourn)
library(shiny)
library(xtable)
library(knitr)
library(ggvis)
setwd("D:/libraries/StratTourn")

tourn = load.tournament("Tourn_Noisy_PD_20140721_202445.Rdata")
# Data for each match
md = tourn$dt
md = add.other.var(md,c("strat","u"))
md$delta.u = md$u - md$other.u
# Names of all strategies
strats = unique(md$strat)

used.strats = strats
shown.strats = strats

```

```{r "ggvis_duels", echo=FALSE, results='asis', fig.width=10, output.type="ggvis"}
d= get.matches.vs.grid(md)

if (TRUE) {
  d$date=2001
  d$size = 1
  p = gvisMotionChart(d, idvar = "pair", timevar = "date", xvar = "u1",
  yvar = "u2", colorvar = "strat2", sizevar = "size", 
  options = list())

  print(p, tag="chart")
  
}
if (!TRUE) {
library(ggplot2)
qplot(data=d, x=u1,y=u2, color=strat1,shape=strat2, geom="point",size=I(4), main="Payoffs of strategy duels")
}


if (!TRUE) {
library(ggvis)

tooltip_fun <- function(x) {
  if(is.null(x)) return(NULL)
  paste0(x$strat1, " vs ", x$strat2,"\n<br>\n",round(x$u1,2), " vs ",round(x$u2,2))
}

gg = ggvis(data=d, x=~u1, y=~u2,stroke=~strat1,fill=~strat1, shape=~strat2) %>%
  layer_points() %>% 
  add_legend(c("fill","stroke", "shape"), title="strat1: color vs strat2: shape") %>%
  add_tooltip(tooltip_fun, "hover")

#print(gg)
gg
}

```

The figure illustrates the payoffs of all strategy duels graphically. The color represent strategy 1 (or strategy 2).


