---
title: "Ranking of strategies"
tab_label: "matches" 
output: html_document
---

```{r "init_data", include=FALSE}
library(StratTourn)
library(shiny)
library(xtable)
library(knitr)
setwd("D:/libraries/StratTourn")

tourn = load.tournament("Tourn_Noisy_PD_20140721_202445.Rdata")
# Data for each match
md = tourn$dt
md = add.other.var(md,c("strat","u"))
md$delta.u = md$u - md$other.u
# Names of all strategies
strats = unique(md$strat)

used.strats = strats
shown.strats = strats

```

## Payoff matrix

```{r, echo=FALSE, results='asis'}
view(
  get.matches.vs.matrix(md, br.sign="*"), rownames.shiny = TRUE
)
#d= get.matches.vs.grid(md)
#library(ggplot2)
#qplot(data=d, x=u1,y=u2, color=strat1,shape=strat2, geom="point",size=I(4), main="Payoffs of strategy pairs")
```

The table shows the average payoffs that the row strategy achieves against the column strategy. By comparing the rows you see how successful strategies and against which strategies. By comparing the column you see which strategies tend to be *nicer* in the sense that the row strategies get higher payoffs.


