```{r "init_data", include=FALSE}
library(StratTourn)
library(shiny)
library(xtable)
library(knitr)
setwd("D:/libraries/StratTourn/studies")

tourn = load.tournament("Tourn_Noisy_PD_20140910_143903_2.tou")
# Data for each match
md = tourn$dt
md = add.other.var(md,c("strat","u"))
md$delta.u = md$u - md$other.u
# Names of all strategies
strats = unique(md$strat)

used.strats = strats
shown.strats = strats
rank.dt = strat.rank.from.matches(md)


```

## Payoff differences
```{r, echo=FALSE,results='asis', fig.width=7, fig.height=7}
d= get.matches.vs.grid(md)
d$u1_minus_u2 = round(d$u1-d$u2,3)
d = arrange(d,-u1_minus_u2)
d = filter(d, u1_minus_u2>=0 | strat1==strat2)
d = mutate(d, share1=round(share1*100,1),share2=round(share2*100,1),
              u1 = round(u1,3), u2=round(u2,3))

rank.df = as.data.frame(rank.dt)
rownames(rank.df) = rank.df$strat
d$ranks = paste0(rank.df[d$strat1,"rank"],", ",rank.df[d$strat2,"rank"])

d = select(d, strat1, strat2, ranks, share1, share2, u1,u2, u1_minus_u2)
view(d)
```

## Average payoff
```{r, echo=FALSE,results='asis', fig.width=7, fig.height=7}
d= get.matches.vs.grid(md)
d$mean.u = round((d$u1+d$u2)/2,3)
d = arrange(d,-mean.u)
d = mutate(d, share1=round(share1*100,1),share2=round(share2*100,1),
              u1 = round(u1,3), u2=round(u2,3))
rank.df = as.data.frame(rank.dt)
rownames(rank.df) = rank.df$strat
d$ranks = paste0(rank.df[d$strat1,"rank"],", ",rank.df[d$strat2,"rank"])

d = select(d, strat1, strat2, ranks, share1, share2, u1,u2, mean.u)
view(d)
```
